---
title: DV_RProject2
author: Brian Yeh, Valentina Chen
output: html_document
---

```{r echo=FALSE, message=FALSE}
setwd("C:/Users/Brian Yeh/Github/DataVisualization/DV_RProject2/00 Doc")
require("jsonlite")
require("RCurl")
require(extrafont)
require(tidyr)
require(dplyr)
require(ggplot2)

  
```

###Summary of dataframe  
SQL Query: select * from titanic
```{r echo=FALSE}
source("../01 Data/Dataframes_All.R", echo = TRUE)
summary(df)
```
  
###Subset of dataframe: White Males with traffic citations who drive BMW's
```{r}
df.sub <- subset(df, GENDER == "M" & RACE == "WHITE" & VIOLATION_TYPE == "Citation" & MAKE == "BMW")
df.sub
```
  
###What percentages of Warnings and Citations are given out to each race?
```{r}

df %>%  filter(VIOLATION_TYPE %in% c("Citation", "Warning")) %>%  group_by(VIOLATION_TYPE, RACE) %>% summarise(count = n()) %>% arrange(VIOLATION_TYPE, count) %>% group_by(VIOLATION_TYPE) %>% mutate(totEach = sum(count)) %>% group_by(RACE, add=TRUE) %>% mutate(percentage_of_total=round(100*count/totEach,2)) %>% ggplot(., aes(x= RACE, y = percentage_of_total, color = RACE, fill=RACE)) + geom_bar(stat = "identity") + facet_wrap(~VIOLATION_TYPE) +theme(axis.text.x = element_blank(), axis.ticks = element_blank())


```

###Which subagency gives out the most Warnings?
```{r}
df %>% filter(VIOLATION_TYPE %in% c("Warning"), VEHICLETYPE %in% c("02 - Automobile")) %>% group_by(VEHICLETYPE, SUBAGENCY) %>% summarise(count = n()) %>% arrange(count) %>% ggplot(., aes(x = VEHICLETYPE, y = count, color = SUBAGENCY, fill = SUBAGENCY)) + geom_bar(position = "dodge", stat = "identity") + scale_y_continuous()+ facet_grid(~VEHICLETYPE) + theme(text = element_text(size=12), axis.text.x = element_blank())

```

###Which Gender is more likely to get off with a warning?
```{r}
df %>%  filter(VIOLATION_TYPE %in% c("Citation", "Warning"), GENDER %in% c("F", "M")) %>%  group_by(VIOLATION_TYPE, GENDER) %>% summarise(count = n()) %>% arrange(VIOLATION_TYPE, count) %>% group_by(VIOLATION_TYPE) %>% mutate(totEach = sum(count)) %>% group_by(GENDER, add=TRUE) %>% mutate(percentage_of_total=round(100*count/totEach,2)) %>% ggplot(., aes(x=VIOLATION_TYPE, y = percentage_of_total, fill= GENDER)) + geom_bar(stat = "identity")

```

